import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'admin',
      email: 'admin@admin.com',
      password: bcrypt.hashSync('admin'),
      isAdmin: true,
    },
    {
      name: 'james',
      email: 'james@james.com',
      password: bcrypt.hashSync('james'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Rhino Cement',
      slug: 'rhino-cement',
      category: 'Cement',
      image: '/images/rhinocement.jpg', // 679px × 829px
      price: 420,
      countInStock: 10,
      brand: 'Rhino',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Cement',
    },
    {
      // _id: '2',
      name: 'Simba Cement',
      slug: 'simba-cemnet',
      category: 'Cement',
      image: '/images/simbas.jpg',
      price: 250,
      countInStock: 0,
      brand: 'simba',
      rating: 4.0,
      numReviews: 10,
      description: 'Cheap but Quality Cement',
    },
    {
      // _id: '3',
      name: 'Blue Triangle Cement',
      slug: 'blue-cement',
      category: 'Cement',
      image: '/images/blueCement.jpeg',
      price: 225,
      countInStock: 15,
      brand: 'triangle',
      rating: 4.5,
      numReviews: 14,
      description: 'The Cement Of Ages',
    },
    {
      // _id: '4',
      name: 'Binding Wire',
      slug: 'binding-wire',
      category: 'Binding Wire',
      image: '/images/Binding-wire.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '5',
      name: 'Construction Machinery',
      slug: 'construction-machinery',
      category: 'Machinery',
      image: '/images/machine.jpg',
      price: 65,
      countInStock: 5,
      brand: 'machinery',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',  
    },
    {
      // _id: '6',
      name: 'Construction Steel',
      slug: 'construction-steel',
      category: 'Steel',
      image: '/images/squerestee.jpeg',
      price: 65,
      countInStock: 5,
      brand: 'steel',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
