const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export const citiesData = [
  { city: 'New York', state: 'NY' },
  { city: 'Los Angeles', state: 'CA' },
  { city: 'Chicago', state: 'IL' },
  { city: 'Houston', state: 'TX' },
  { city: 'Phoenix', state: 'AZ' },
  { city: 'Philadelphia', state: 'PA' },
  { city: 'San Antonio', state: 'TX' },
  { city: 'San Diego', state: 'CA' },
  { city: 'Dallas', state: 'TX' },
  { city: 'San Jose', state: 'CA' },
  { city: 'Austin', state: 'TX' },
  { city: 'Jacksonville', state: 'FL' },
  { city: 'San Francisco', state: 'CA' },
  { city: 'Columbus', state: 'OH' },
  { city: 'Indianapolis', state: 'IN' },
  { city: 'Fort Worth', state: 'TX' },
  { city: 'Charlotte', state: 'NC' },
  { city: 'Seattle', state: 'WA' },
  { city: 'Denver', state: 'CO' },
  { city: 'Washington', state: 'DC' },
  { city: 'Boston', state: 'MA' },
  { city: 'El Paso', state: 'TX' },
  { city: 'Nashville', state: 'TN' },
  { city: 'Detroit', state: 'MI' },
  { city: 'Portland', state: 'OR' },
  { city: 'Memphis', state: 'TN' },
  { city: 'Oklahoma City', state: 'OK' },
  { city: 'Las Vegas', state: 'NV' },
  { city: 'Louisville', state: 'KY' },
  { city: 'Baltimore', state: 'MD' },
  { city: 'Milwaukee', state: 'WI' },
  { city: 'Albuquerque', state: 'NM' },
  { city: 'Tucson', state: 'AZ' },
  { city: 'Fresno', state: 'CA' },
  { city: 'Mesa', state: 'AZ' },
  { city: 'Sacramento', state: 'CA' },
  { city: 'Atlanta', state: 'GA' },
  { city: 'Kansas City', state: 'MO' },
  { city: 'Colorado Springs', state: 'CO' },
  { city: 'Miami', state: 'FL' },
  { city: 'Raleigh', state: 'NC' },
  { city: 'Omaha', state: 'NE' },
  { city: 'Long Beach', state: 'CA' },
  { city: 'Virginia Beach', state: 'VA' },
  { city: 'Oakland', state: 'CA' },
  { city: 'Minneapolis', state: 'MN' },
  { city: 'Tulsa', state: 'OK' },
  { city: 'Arlington', state: 'TX' },
  { city: 'New Orleans', state: 'LA' },
  { city: 'Wichita', state: 'KS' },
  { city: 'Cleveland', state: 'OH' },
  { city: 'Tampa', state: 'FL' },
  { city: 'Bakersfield', state: 'CA' },
  { city: 'Aurora', state: 'CO' },
  { city: 'Anaheim', state: 'CA' },
  { city: 'Honolulu', state: 'HI' },
  { city: 'Santa Ana', state: 'CA' },
  { city: 'Riverside', state: 'CA' },
  { city: 'Corpus Christi', state: 'TX' },
  { city: 'Lexington', state: 'KY' },
  { city: 'Pittsburgh', state: 'PA' },
  { city: 'Anchorage', state: 'AK' },
  { city: 'Stockton', state: 'CA' },
  { city: 'Cincinnati', state: 'OH' },
  { city: 'St. Louis', state: 'MO' },
  { city: 'Orlando', state: 'FL' },
  { city: 'Buffalo', state: 'NY' },
  { city: 'Madison', state: 'WI' },
  { city: 'Norfolk', state: 'VA' },
  { city: 'Chandler', state: 'AZ' },
  { city: 'Fort Wayne', state: 'IN' },
  { city: 'Jersey City', state: 'NJ' },
  { city: 'Durham', state: 'NC' },
  { city: 'St. Petersburg', state: 'FL' },
  { city: 'Laredo', state: 'TX' },
  { city: 'Lubbock', state: 'TX' },
  { city: 'Winston-Salem', state: 'NC' },
  { city: 'Garland', state: 'TX' },
  { city: 'Glendale', state: 'AZ' },
  { city: 'Hialeah', state: 'FL' },
  { city: 'Reno', state: 'NV' },
  { city: 'Baton Rouge', state: 'LA' },
  { city: 'Irving', state: 'TX' },
  { city: 'Chesapeake', state: 'VA' },
  { city: 'Scottsdale', state: 'AZ' },
  { city: 'North Las Vegas', state: 'NV' },
  { city: 'Fremont', state: 'CA' },
  { city: 'Gilbert', state: 'AZ' },
  { city: 'San Bernardino', state: 'CA' },
  { city: 'Boise', state: 'ID' },
  { city: 'Birmingham', state: 'AL' },
  { city: 'Richmond', state: 'VA' },
  { city: 'Des Moines', state: 'IA' },
  { city: 'Spokane', state: 'WA' },
  { city: 'Montgomery', state: 'AL' },
  { city: 'Modesto', state: 'CA' },
  { city: 'Fayetteville', state: 'NC' },
  { city: 'Tacoma', state: 'WA' },
  { city: 'Shreveport', state: 'LA' },
  { city: 'Fontana', state: 'CA' },
  { city: 'Oxnard', state: 'CA' },
  { city: 'Aurora', state: 'IL' },
  { city: 'Moreno Valley', state: 'CA' },
  { city: 'Akron', state: 'OH' },
  { city: 'Yonkers', state: 'NY' },
  { city: 'Augusta', state: 'GA' },
  { city: 'Little Rock', state: 'AR' },
  { city: 'Glendale', state: 'CA' },
  { city: 'Huntsville', state: 'AL' },
  { city: 'Amarillo', state: 'TX' },
  { city: 'Grand Rapids', state: 'MI' },
  { city: 'Salt Lake City', state: 'UT' },
  { city: 'Mobile', state: 'AL' },
  { city: 'Tallahassee', state: 'FL' },
  { city: 'Huntington Beach', state: 'CA' },
  { city: 'Grand Prairie', state: 'TX' },
  { city: 'Overland Park', state: 'KS' },
  { city: 'Tucson', state: 'AZ' },
  { city: 'Knoxville', state: 'TN' },
  { city: 'Worcester', state: 'MA' },
  { city: 'Newport News', state: 'VA' },
  { city: 'Brownsville', state: 'TX' },
  { city: 'Santa Clarita', state: 'CA' },
  { city: 'Providence', state: 'RI' },
  { city: 'Fort Lauderdale', state: 'FL' },
  { city: 'Garden Grove', state: 'CA' },
  { city: 'Oceanside', state: 'CA' },
  { city: 'Rancho Cucamonga', state: 'CA' },
  { city: 'Santa Rosa', state: 'CA' },
  { city: 'Ontario', state: 'CA' },
  { city: 'Chattanooga', state: 'TN' },
  { city: 'Tempe', state: 'AZ' },
  { city: 'Springfield', state: 'MO' },
  { city: 'Rockford', state: 'IL' },
  { city: 'Clarksville', state: 'TN' },
  { city: 'Peoria', state: 'AZ' },
  { city: 'Fort Collins', state: 'CO' },
  { city: 'Lancaster', state: 'CA' },
  { city: 'Cary', state: 'NC' },
  { city: 'Salinas', state: 'CA' },
  { city: 'Palmdale', state: 'CA' },
  { city: 'Hayward', state: 'CA' },
  { city: 'Pomona', state: 'CA' },
  { city: 'Escondido', state: 'CA' },
  { city: 'Sunnyvale', state: 'CA' },
  { city: 'Alexandria', state: 'VA' },
  { city: 'Lakewood', state: 'CO' },
  { city: 'Hollywood', state: 'FL' },
  { city: 'Paterson', state: 'NJ' },
  { city: 'Syracuse', state: 'NY' },
  { city: 'Naperville', state: 'IL' },
  { city: 'McKinney', state: 'TX' },
  { city: 'Mesquite', state: 'TX' },
  { city: 'Savannah', state: 'GA' },
  { city: 'Dayton', state: 'OH' },
  { city: 'Bridgeport', state: 'CT' },
  { city: 'Orange', state: 'CA' },
  { city: 'Fullerton', state: 'CA' },
  { city: 'Pasadena', state: 'TX' },
  { city: 'Hampton', state: 'VA' },
  { city: 'McAllen', state: 'TX' },
];

export const nationsData = [
  { name: 'Afghanistan', shortForm: 'AF' },
  { name: 'Albania', shortForm: 'AL' },
  { name: 'Algeria', shortForm: 'DZ' },
  { name: 'Andorra', shortForm: 'AD' },
  { name: 'Angola', shortForm: 'AO' },
  { name: 'Antigua and Barbuda', shortForm: 'AG' },
  { name: 'Argentina', shortForm: 'AR' },
  { name: 'Armenia', shortForm: 'AM' },
  { name: 'Australia', shortForm: 'AU' },
  { name: 'Austria', shortForm: 'AT' },
  { name: 'Azerbaijan', shortForm: 'AZ' },
  { name: 'Bahamas', shortForm: 'BS' },
  { name: 'Bahrain', shortForm: 'BH' },
  { name: 'Bangladesh', shortForm: 'BD' },
  { name: 'Barbados', shortForm: 'BB' },
  { name: 'Belarus', shortForm: 'BY' },
  { name: 'Belgium', shortForm: 'BE' },
  { name: 'Belize', shortForm: 'BZ' },
  { name: 'Benin', shortForm: 'BJ' },
  { name: 'Bhutan', shortForm: 'BT' },
  { name: 'Bolivia', shortForm: 'BO' },
  { name: 'Bosnia and Herzegovina', shortForm: 'BA' },
  { name: 'Botswana', shortForm: 'BW' },
  { name: 'Brazil', shortForm: 'BR' },
  { name: 'Brunei', shortForm: 'BN' },
  { name: 'Bulgaria', shortForm: 'BG' },
  { name: 'Burkina Faso', shortForm: 'BF' },
  { name: 'Burundi', shortForm: 'BI' },
  { name: 'Cambodia', shortForm: 'KH' },
  { name: 'Cameroon', shortForm: 'CM' },
  { name: 'Canada', shortForm: 'CA' },
  { name: 'Cape Verde', shortForm: 'CV' },
  { name: 'Central African Republic', shortForm: 'CF' },
  { name: 'Chad', shortForm: 'TD' },
  { name: 'Chile', shortForm: 'CL' },
  { name: 'China', shortForm: 'CN' },
  { name: 'Colombia', shortForm: 'CO' },
  { name: 'Comoros', shortForm: 'KM' },
  { name: 'Congo (Brazzaville)', shortForm: 'CG' },
  { name: 'Congo (Kinshasa)', shortForm: 'CD' },
  { name: 'Costa Rica', shortForm: 'CR' },
  { name: "Cote d'Ivoire", shortForm: 'CI' },
  { name: 'Croatia', shortForm: 'HR' },
  { name: 'Cuba', shortForm: 'CU' },
  { name: 'Cyprus', shortForm: 'CY' },
  { name: 'Czech Republic', shortForm: 'CZ' },
  { name: 'Denmark', shortForm: 'DK' },
  { name: 'Djibouti', shortForm: 'DJ' },
  { name: 'Dominica', shortForm: 'DM' },
  { name: 'Dominican Republic', shortForm: 'DO' },
  { name: 'East Timor', shortForm: 'TL' },
  { name: 'Ecuador', shortForm: 'EC' },
  { name: 'Egypt', shortForm: 'EG' },
  { name: 'El Salvador', shortForm: 'SV' },
  { name: 'Equatorial Guinea', shortForm: 'GQ' },
  { name: 'Eritrea', shortForm: 'ER' },
  { name: 'Estonia', shortForm: 'EE' },
  { name: 'Ethiopia', shortForm: 'ET' },
  { name: 'Fiji', shortForm: 'FJ' },
  { name: 'Finland', shortForm: 'FI' },
  { name: 'France', shortForm: 'FR' },
  { name: 'Gabon', shortForm: 'GA' },
  { name: 'Gambia', shortForm: 'GM' },
  { name: 'Georgia', shortForm: 'GE' },
  { name: 'Germany', shortForm: 'DE' },
  { name: 'Ghana', shortForm: 'GH' },
  { name: 'Greece', shortForm: 'GR' },
  { name: 'Grenada', shortForm: 'GD' },
  { name: 'Guatemala', shortForm: 'GT' },
  { name: 'Guinea', shortForm: 'GN' },
  { name: 'Guinea-Bissau', shortForm: 'GW' },
  { name: 'Guyana', shortForm: 'GY' },
  { name: 'Haiti', shortForm: 'HT' },
  { name: 'Honduras', shortForm: 'HN' },
  { name: 'Hungary', shortForm: 'HU' },
  { name: 'Iceland', shortForm: 'IS' },
  { name: 'India', shortForm: 'IN' },
  { name: 'Indonesia', shortForm: 'ID' },
  { name: 'Iran', shortForm: 'IR' },
  { name: 'Iraq', shortForm: 'IQ' },
  { name: 'Ireland', shortForm: 'IE' },
  { name: 'Israel', shortForm: 'IL' },
  { name: 'Italy', shortForm: 'IT' },
  { name: 'Jamaica', shortForm: 'JM' },
  { name: 'Japan', shortForm: 'JP' },
  { name: 'Jordan', shortForm: 'JO' },
  { name: 'Kazakhstan', shortForm: 'KZ' },
  { name: 'Kenya', shortForm: 'KE' },
  { name: 'Kiribati', shortForm: 'KI' },
  { name: 'Korea, North', shortForm: 'KP' },
  { name: 'Korea, South', shortForm: 'KR' },
  { name: 'Kosovo', shortForm: 'XK' },
  { name: 'Kuwait', shortForm: 'KW' },
  { name: 'Kyrgyzstan', shortForm: 'KG' },
  { name: 'Laos', shortForm: 'LA' },
  { name: 'Latvia', shortForm: 'LV' },
  { name: 'Lebanon', shortForm: 'LB' },
  { name: 'Lesotho', shortForm: 'LS' },
  { name: 'Liberia', shortForm: 'LR' },
  { name: 'Libya', shortForm: 'LY' },
  { name: 'Liechtenstein', shortForm: 'LI' },
  { name: 'Lithuania', shortForm: 'LT' },
  { name: 'Luxembourg', shortForm: 'LU' },
  { name: 'Madagascar', shortForm: 'MG' },
  { name: 'Malawi', shortForm: 'MW' },
  { name: 'Malaysia', shortForm: 'MY' },
  { name: 'Maldives', shortForm: 'MV' },
  { name: 'Mali', shortForm: 'ML' },
  { name: 'Malta', shortForm: 'MT' },
  { name: 'Marshall Islands', shortForm: 'MH' },
  { name: 'Mauritania', shortForm: 'MR' },
  { name: 'Mauritius', shortForm: 'MU' },
  { name: 'Mexico', shortForm: 'MX' },
  { name: 'Micronesia', shortForm: 'FM' },
  { name: 'Moldova', shortForm: 'MD' },
  { name: 'Monaco', shortForm: 'MC' },
  { name: 'Mongolia', shortForm: 'MN' },
  { name: 'Montenegro', shortForm: 'ME' },
  { name: 'Morocco', shortForm: 'MA' },
  { name: 'Mozambique', shortForm: 'MZ' },
  { name: 'Myanmar', shortForm: 'MM' },
  { name: 'Namibia', shortForm: 'NA' },
  { name: 'Nauru', shortForm: 'NR' },
  { name: 'Nepal', shortForm: 'NP' },
  { name: 'Netherlands', shortForm: 'NL' },
  { name: 'New Zealand', shortForm: 'NZ' },
  { name: 'Nicaragua', shortForm: 'NI' },
  { name: 'Niger', shortForm: 'NE' },
  { name: 'Nigeria', shortForm: 'NG' },
  { name: 'North Macedonia', shortForm: 'MK' },
  { name: 'Norway', shortForm: 'NO' },
  { name: 'Oman', shortForm: 'OM' },
  { name: 'Pakistan', shortForm: 'PK' },
  { name: 'Palau', shortForm: 'PW' },
  { name: 'Panama', shortForm: 'PA' },
  { name: 'Papua New Guinea', shortForm: 'PG' },
  { name: 'Paraguay', shortForm: 'PY' },
  { name: 'Peru', shortForm: 'PE' },
  { name: 'Philippines', shortForm: 'PH' },
  { name: 'Poland', shortForm: 'PL' },
  { name: 'Portugal', shortForm: 'PT' },
  { name: 'Qatar', shortForm: 'QA' },
  { name: 'Romania', shortForm: 'RO' },
  { name: 'Russia', shortForm: 'RU' },
  { name: 'Rwanda', shortForm: 'RW' },
  { name: 'Saint Kitts and Nevis', shortForm: 'KN' },
  { name: 'Saint Lucia', shortForm: 'LC' },
  { name: 'Saint Vincent and the Grenadines', shortForm: 'VC' },
  { name: 'Samoa', shortForm: 'WS' },
  { name: 'San Marino', shortForm: 'SM' },
  { name: 'Sao Tome and Principe', shortForm: 'ST' },
  { name: 'Saudi Arabia', shortForm: 'SA' },
  { name: 'Senegal', shortForm: 'SN' },
  { name: 'Serbia', shortForm: 'RS' },
  { name: 'Seychelles', shortForm: 'SC' },
  { name: 'Sierra Leone', shortForm: 'SL' },
  { name: 'Singapore', shortForm: 'SG' },
  { name: 'Slovakia', shortForm: 'SK' },
  { name: 'Slovenia', shortForm: 'SI' },
  { name: 'Solomon Islands', shortForm: 'SB' },
  { name: 'Somalia', shortForm: 'SO' },
  { name: 'South Africa', shortForm: 'ZA' },
  { name: 'South Sudan', shortForm: 'SS' },
  { name: 'Spain', shortForm: 'ES' },
  { name: 'Sri Lanka', shortForm: 'LK' },
  { name: 'Sudan', shortForm: 'SD' },
  { name: 'Suriname', shortForm: 'SR' },
  { name: 'Sweden', shortForm: 'SE' },
  { name: 'Switzerland', shortForm: 'CH' },
  { name: 'Syria', shortForm: 'SY' },
  { name: 'Taiwan', shortForm: 'TW' },
  { name: 'Tajikistan', shortForm: 'TJ' },
  { name: 'Tanzania', shortForm: 'TZ' },
  { name: 'Thailand', shortForm: 'TH' },
  { name: 'Togo', shortForm: 'TG' },
  { name: 'Tonga', shortForm: 'TO' },
  { name: 'Trinidad and Tobago', shortForm: 'TT' },
  { name: 'Tunisia', shortForm: 'TN' },
  { name: 'Turkey', shortForm: 'TR' },
  { name: 'Turkmenistan', shortForm: 'TM' },
  { name: 'Tuvalu', shortForm: 'TV' },
  { name: 'Uganda', shortForm: 'UG' },
  { name: 'Ukraine', shortForm: 'UA' },
  { name: 'United Arab Emirates', shortForm: 'AE' },
  { name: 'United Kingdom', shortForm: 'GB' },
  { name: 'United States', shortForm: 'US' },
  { name: 'Uruguay', shortForm: 'UY' },
  { name: 'Uzbekistan', shortForm: 'UZ' },
  { name: 'Vanuatu', shortForm: 'VU' },
  { name: 'Vatican City', shortForm: 'VA' },
  { name: 'Venezuela', shortForm: 'VE' },
  { name: 'Vietnam', shortForm: 'VN' },
  { name: 'Yemen', shortForm: 'YE' },
  { name: 'Zambia', shortForm: 'ZM' },
  { name: 'Zimbabwe', shortForm: 'ZW' },
];

export default data;
